name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:    
      matrix:
        arch: [64] #, 32

    steps:
    # Install dependencies
    - name: Install ck
      run: sudo apt-get install libck-dev    
    - name: Check out cyclone
      uses: actions/checkout@master
      with:
        repository: justinethier/cyclone-bootstrap
    - name: Cache compiled Cyclone files
      uses: actions/cache@v1
      env:
        cache-name: cache-cyclone
      with:
        path: cyclone-bootstrap
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        #key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}:  
        #restore-keys: |
        #  ${{ runner.os }}-build-${{ env.cache-name }}-
        #  ${{ runner.os }}-build-
        #  ${{ runner.os }}-          
    - name: make
      if: steps.cache-cyclone.cache-hit != 'true'
      run: make
    - name: make install
      run: sudo make install
    - name: make test
      run: make test
      
    # Build and test our library
    - uses: actions/checkout@v2
    - name: Build array-list
      run: cyclone cyclone/array-list.sld
    - name: Run tests
      run: |
        cyclone array-list-tests.scm
        ./array-list-tests

